title: Kristen Gilden
tagline: a personal blog
author:
  name: 'Kristen Gilden'
  twitter: k_gilden

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'kg-personal-blog'

google-ID: 'UA-107693311-1'

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/kgilden'}
- {icon: 'twitter', link: 'https://twitter.com/k_gilden'}
- {icon: 'facebook', link: 'https://facebook.com/kristen.gilden'}
- {icon: 'envelope', link: 'mailto:kristen.gilden+blog@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
